### ISSUE TITLE
Request debug console?

### ISSUE THREAD

**Issue by petri** [vfaronov/turq#7]
Is there a way to show what the HTTP client sent? That would be useful.

**Comment by petri** [comment]
Granted, the server console log shows some of the stuff. But it would be nice if there was a console that showed the full request contents, or even the last request. For my use case I am POSTing a fairly complex XML doc for example; checking that in console log is not really pleasing ;)

**Comment by vfaronov** [comment]
This is definitely something I’d like to add, but to be honest Turq is low on my priorities list at the moment, so this is unlikely to be done in the near future. For the time being, as a workaround, you can write a custom handler that simply dumps the request data to a file.

**Comment by vfaronov** [comment]
I am rewriting Turq from scratch on the [overhaul](https://github.com/vfaronov/turq/tree/overhaul) branch, and hope to release it soon as version 0.3.

This issue is partly addressed in the new Turq with a `debug()` call that enables more verbose logging to the (system) console, including request and response headers.

However, `debug()` does not try to show the request body, as that can be very long and binary.

My current thinking is that full and detailed request/response display is out of scope for Turq. Instead, one can put [mitmproxy](https://mitmproxy.org/) (or some similar tool) in front of Turq. mitmproxy already solves the display problem very nicely, with pretty-printing for multiple formats etc.

That said, it’s not hard for me to also add a `dump()` call to the rules language, which would dump the request body to a temporary file and then print the name of that file to the (system) console.

@petri In case you still remember your original use case, would it be helped by any of the above?

**Comment by vfaronov** [comment]
Released Turq 0.3.1 with `debug()` as explained above.
